language: python
matrix:
  include:
  - os: osx
    python: '2.7'
    language: generic
install:
  - pip install -r requirements.txt
  - sudo mkdir /usr/local/man
  - sudo chmod a+w /usr/local/man
script:
  - python test/__init__.py
deploy:
  provider: pypi
  user: "qta"
  password: 
    secure: BRukPB27oCtxWgoCI4ERD7Bn/coAYlRl8zrmb9qsI9zOsK8FheLbOGHkmZ0voYUtPNgFt8yOBAZgfJeCKAE64ABgDzHtZoTbZVfmtOaGT0bREknURQMU4+HFaoZGc0DqOnC8fk0MkoCVJxzuxFMD4AyJlsLZghH2LDDCXICsS36mBI+yFY3zmcIuvRlmmpFx1xI8XicFlz7w5oqoRiHzXO6oFweyIV+8Z5k5M1A4VQZ8/NhrDIGV4gCrqNsIOKmqVgtYpeXy+NYlH3gLPOS5MTIukrirr4VJyGTwz6JzZiZdukgetqfEGutTp9FHZ1p/qGgSRSZbRAZnW7XLAN8lY71BeIa3If+hJ6UwP4rkb/PGOoq3u0MF2NiMNkaLVZX+shtiJaUQAfft509WWDcl2DbMtlwJtJ/eL7HGI6K0K9VnWA5Z6NCXpHFsmIazoA0Ye9vPYF49Lwi0NJTxyZ5JItrViM9/t2+vi1bcEjuWoIF+//ohSZX090Pio8Wg1UZt18xZf1qlVESfPOACPxn6g2ahCYvpKXinZhlG7lZBIXbx3+DlQSnMWCQUuCn20bsisIt/0aEetdA/VF/bF/1XpApLwm5/vjfTr1ZX+wYc7gt756LqVCQWlv9QOL3pJepv1zMapUNwRN0EEcHMJOOcOgZ59CxnJkkfK8Gbn8v74KA=
  distributions: sdist bdist_egg
  on:
    tags: true
    branch: master
